In [13]:
import transformers
import tensorflow as tf
import numpy as np

In [2]:
model = transformers.TFDistilBertForMaskedLM.from_pretrained('distilbert-base-uncased')

In [3]:
tokenizer = transformers.DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
tokenizer.tokenize("If your money is tight, don't cut corners.")

['if',
 'your',
 'money',
 'is',
 'tight',
 ',',
 'don',
 "'",
 't',
 'cut',
 'corners',
 '.']

In [45]:
input_toks = tokenizer.encode("If your money is tight, don't cut corners")
input_toks

[101, 2065, 2115, 2769, 2003, 4389, 1010, 2123, 1005, 1056, 3013, 8413, 102]

In [33]:
tokenizer.convert_ids_to_tokens(input_toks)

['[CLS]',
 'if',
 'your',
 'money',
 'is',
 'tight',
 ',',
 'don',
 "'",
 't',
 'cut',
 'corners',
 '[SEP]']

In [34]:
input_mat = np.array(input_toks).reshape((1,-1))  # get a 1 x len(input_toks) matr
outputs = model.predict(input_mat)
predictions = outputs[0]
predictions

array([[[ -6.588945 ,  -6.557416 ,  -6.5452743, ...,  -5.897119 ,
          -5.748498 ,  -3.4113202],
        [-10.572553 , -10.322592 , -10.491317 , ..., -10.18239  ,
          -7.0187483,  -6.8466444],
        [-13.142289 , -13.421929 , -13.51027  , ..., -10.972868 ,
          -9.495082 ,  -9.03601  ],
        ...,
        [-11.542616 , -11.647187 , -11.60502  , ..., -10.519468 ,
          -8.527291 , -10.500184 ],
        [ -8.514042 ,  -8.798411 ,  -8.522595 , ...,  -8.86088  ,
          -6.9834356,  -2.3236327],
        [-12.030145 , -12.328578 , -12.353381 , ..., -10.730778 ,
         -10.089339 ,  -7.104043 ]]], dtype=float32)

In [35]:
predictions.shape  
# the output is for a single input (first dimension), thirteen tokens (including [CLS] and [SEP], second dimension), 
# and a vocabulary of size 30522

(1, 13, 30522)

In [38]:
# We can look at the predictions for the target word (at position 5)
predictions[0,5]

array([-9.633262 , -9.816528 , -9.4804325, ..., -8.620858 , -6.931823 ,
       -4.441987 ], dtype=float32)

In [39]:
best_words = np.argsort(predictions[0][5])[::-1] # Sort in increasing order
best_words

array([ 4389,  2485,  6065, ..., 25084, 12112, 24546])

In [40]:
tokenizer.convert_ids_to_tokens(best_words[:10])

['tight',
 'close',
 'loose',
 'deep',
 'big',
 'tighter',
 'tied',
 'firm',
 'hard',
 'down']

In [46]:
# mask the target word.
input_toks = tokenizer.encode("If your money is [MASK], don't cut corners")
input_mat = np.array(input_toks).reshape((1,-1))
outputs = model.predict(input_mat)
predictions = outputs[0]
best_words = np.argsort(predictions[0][5])[::-1] # Sort in increasing order
tokenizer.convert_ids_to_tokens(best_words)

['stolen',
 'wasted',
 'worthless',
 'dirty',
 'yours',
 'lost',
 'money',
 'worth',
 'good',
 'bad',
 'wrong',
 'crooked',
 'real',
 'valuable',
 'small',
 'paid',
 'scarce',
 'low',
 'precious',
 'enough',
 'borrowed',
 'cheap',
 'broken',
 'tight',
 'invested',
 'gone',
 'big',
 'safe',
 'mine',
 'nothing',
 'right',
 'greedy',
 'ruined',
 'not',
 'empty',
 'rich',
 'saved',
 'hidden',
 'spent',
 'flat',
 'useless',
 'fine',
 'expensive',
 'here',
 'needed',
 'pocket',
 'high',
 'loaded',
 'missing',
 'insufficient',
 'earned',
 'important',
 'dangerous',
 'cut',
 'made',
 'slim',
 'okay',
 'bigger',
 'depleted',
 'fake',
 'illegal',
 'used',
 'anything',
 'dollars',
 'generous',
 'spilled',
 'lonely',
 'there',
 'exhausted',
 'full',
 'excessive',
 'outstanding',
 'hurt',
 'divided',
 'idle',
 'down',
 'short',
 'theirs',
 'stupid',
 'taken',
 'split',
 'owed',
 'better',
 'left',
 'thin',
 'available',
 'won',
 'coming',
 'up',
 'interested',
 'dead',
 'sticky',
 'involved',
 'spo

In [52]:
input_toks = tokenizer.encode("If your money is [MASK], don't cut corners")
convert = tokenizer.convert_ids_to_tokens(input_toks)
convert.index('[MASK]')

5

In [42]:
from nltk.corpus import wordnet as wn
word = 'tight'
wn.get_synonyms(word)

AttributeError: 'WordNetCorpusReader' object has no attribute 'get_synonyms'